module.exports = {
  columns: [
    { name: 'Inbox', label: null },
    { name: 'Ideas', label: 'backlog' },
    { name: 'Roadmap', label: 'roadmap' },
    { name: 'Ready', label: 'ready' },
    { name: 'In Progress', label: 'in progress' },
    { name: 'Needs Review', label: 'needs review' },
    { name: 'Done', label: null, closed: true }
  ],
  repositories: [
    'bpmn-io/tasks',
    'bpmn-io/awesome-bpmn-io',
    'bpmn-io/bpmn-font',
    'bpmn-io/bpmn-io-demo',
    'bpmn-io/bpmn-js',
    'bpmn-io/bpmn-js-bpmnlint',
    'bpmn-io/bpmn-js-cli',
    'bpmn-io/bpmn-js-example-angular',
    'bpmn-io/bpmn-js-example-custom-elements',
    'bpmn-io/bpmn-js-examples',
    'bpmn-io/bpmn-js-i18n',
    'bpmn-io/bpmn-js-integration',
    'bpmn-io/bpmn-js-properties-panel',
    'bpmn-io/bpmn-js-signavio-compat',
    'bpmn-io/bpmn-js-sketchy',
    'bpmn-io/bpmn-js-token-simulation',
    'bpmn-io/bpmn-js-token-simulation-plugin',
    'bpmn-io/bpmn-moddle',
    'bpmn-io/bpmn.io',
    'bpmn-io/bpmnlint',
    'bpmn-io/camunda-transaction-boundaries',
    'bpmn-io/cmmn-font',
    'bpmn-io/cmmn-js',
    'bpmn-io/cmmn-js-examples',
    'bpmn-io/cmmn-js-properties-panel',
    'bpmn-io/cmmn-moddle',
    'bpmn-io/diagram-js',
    'bpmn-io/diagram-js-direct-editing',
    'bpmn-io/diagram-js-minimap',
    'bpmn-io/diagram-js-origin',
    'bpmn-io/dmn-font',
    'bpmn-io/dmn-js',
    'bpmn-io/dmn-js-examples',
    'bpmn-io/dmn-js-properties-panel',
    'bpmn-io/dmn-moddle',
    'bpmn-io/internal-docs',
    'bpmn-io/min-dash',
    'bpmn-io/min-dom',
    'bpmn-io/moddle',
    'bpmn-io/moddle-xml',
    'bpmn-io/table-js',
    'bpmn-io/tiny-svg',
    'camunda/camunda-bpmn-moddle',
    'camunda/camunda-cmmn-moddle',
    'camunda/camunda-modeler',
    'camunda/camunda-modeler-plugin-example',
    'camunda/camunda-modeler-plugin-helpers',
    'camunda/camunda-modeler-plugins'
  ]
};